### PR TITLE
Refactor Subrequest

### PR DESCRIPTION
**Pull request by gholt**
Now subrequesting will always copy the auth details over. Had to split
into newSubrequest and serveHTTPSubrequest, but it's pretty much the
same for code that uses it because they all did two steps anyway.

### CODE REVIEW

**Comment by redbo** [comment]
Still looking, but I'm skeptical of this change.  I'm not sure what problem is fixed by re-authenticating every subrequest independently.  I don't think you can "copy" tempurl authentication from request to request.  Authorization function inheritance seemed really elegant for solving those types of problems.

**Comment by redbo** [comment]
Like, all formpost does is set an Authorize function and then call Subrequest for each upload.  This  makes all of those subrequests 401.

**Comment by gholt** [comment]
Yeah, I wanted to post this up for you guys to look at. Test comparisons with master showed I was not done yet (errors went up by dozen or so). I should've made a comment for that.

Anyway, I was going to work on it more but the main purpose was to give a way to get auth info from the main request to the subrequests without a lot of "thinking" by the various middlewares, unless and where they need it.

Your comment about how copying X-Auth-Token was really a great thing to be doing got me thinking about how to solve that. StaticWeb did tons of pretending it knew all about auth.

**Comment by gholt** [comment]
This floated away from what I thought was going to do when I started. I'm going to squash this all down to one commit and repost a new PR.

**Pull request closed without merging**
